# Generated by Django 4.1.5 on 2023-05-09 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsubject', models.CharField(max_length=100)),
                ('jcontent', models.TextField()),
                ('jpubdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('jlikey', models.ManyToManyField(blank=True, related_name='jlikey', to=settings.AUTH_USER_MODEL)),
                ('jwriter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jwriter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jcomment', models.TextField()),
                ('jboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.join')),
                ('jreplyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
